version: '3.8'

services:
  database:
    build: 
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-onboarding-db
    ports:
      - 15432:5432
    networks:
      - app-network

  backend:
    build:
      context: ./backend/employee.onboarding.mngr
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/user-onboarding-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: A5SAdg8gDrZqHkzLlIPXPbmkeqQ5vHNZxsKOpVqReSJPNhJJtNZyLIdUpc1XZF6m
      NEXT_PUBLIC_FRONTEND_URL: http://frontend:3000
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/employees-onboarding-front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    volumes:
      - ./frontend/employees-onboarding-front:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge