services:
  database:
    build: ./postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-onboarding-db
    ports:
      - 15432:5432

  backend:
    build: ./backend/employee.onboarding.mngr
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/user-onboarding-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: A5SAdg8gDrZqHkzLlIPXPbmkeqQ5vHNZxsKOpVqReSJPNhJJtNZyLIdUpc1XZF6m
    depends_on:
      - database
    ports:
      - 8080:8080