name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      SPRING_PROFILES_ACTIVE: qa
      QA_DB_URL: ${{ secrets.QA_DB_URL }}
      QA_DB_USER: ${{ secrets.QA_DB_USER }}
      QA_DB_PASS: ${{ secrets.QA_DB_PASS }}
      QA_JWT_SECRET: ${{ secrets.QA_JWT_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      working-directory: ./backend/employee.onboarding.mngr
      run: mvn package -DskipTests
    - name: Run tests
      working-directory: ./backend/employee.onboarding.mngr
      run: mvn test