name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/employees-onboarding-front/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./frontend/employees-onboarding-front
      run: npm ci
      
    - name: Build project
      working-directory: ./frontend/employees-onboarding-front
      run: npm run build
      
    - name: Run tests
      working-directory: ./frontend/employees-onboarding-front
      run: npm test
      env:
        CI: true